# 输出停顿/换行/退出练习
import time
print("\033[31m这是小说名字\033[0m")
time.sleep(1)
print('------------------------------')
time.sleep(1)
print("作者：马修骑兔兔")
time.sleep(1)
print("软件制作：呢喃 & 马修骑兔兔")
time.sleep(1)
print("\n" )
time.sleep(1)
print("输入角色姓名开始冒险")
input("")
input("\n\n按下 enter 键后退出游戏。")